[2025-03-10T00:17:16.623+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T00:17:16.661+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:16:22.934679+00:00 [queued]>
[2025-03-10T00:17:16.690+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:16:22.934679+00:00 [queued]>
[2025-03-10T00:17:16.690+0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-10T00:17:16.894+0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-03-09 18:16:22.934679+00:00
[2025-03-10T00:17:16.904+0600] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-03-10T00:17:16.913+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'real_time_e2e_dag', 'extract_data_task', 'manual__2025-03-09T18:16:22.934679+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/RT_temp.py', '--cfg-path', '/tmp/tmpmh11_jnc']
[2025-03-10T00:17:16.914+0600] {standard_task_runner.py:105} INFO - Job 22: Subtask extract_data_task
[2025-03-10T00:17:16.919+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=46907) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-10T00:17:16.920+0600] {standard_task_runner.py:72} INFO - Started process 47082 to run task
[2025-03-10T00:17:16.985+0600] {task_command.py:467} INFO - Running <TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:16:22.934679+00:00 [running]> on host shamim-X541UV
[2025-03-10T00:17:17.110+0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='real_time_e2e_dag' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T18:16:22.934679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T18:16:22.934679+00:00'
[2025-03-10T00:17:17.116+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T00:17:17.117+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T00:17:17.118+0600] {logging_mixin.py:190} INFO - Current task name:extract_data_task state:running start_date:2025-03-09 18:17:16.663042+00:00
[2025-03-10T00:17:17.121+0600] {logging_mixin.py:190} INFO - Dag name:real_time_e2e_dag and current dag run status:running
[2025-03-10T00:17:17.121+0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T00:17:23.011+0600] {java_gateway.py:2273} INFO - Callback Server Starting
[2025-03-10T00:17:23.013+0600] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 44917)
[2025-03-10T00:17:29.875+0600] {clientserver.py:561} INFO - Python Server ready to receive messages
[2025-03-10T00:17:29.877+0600] {clientserver.py:575} INFO - Received command c on object id p0
[2025-03-10T00:18:29.559+0600] {clientserver.py:575} INFO - Received command c on object id p0
[2025-03-10T00:20:15.652+0600] {clientserver.py:575} INFO - Received command c on object id p0
[2025-03-10T00:27:15.481+0600] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-03-10T00:27:15.482+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-10T00:27:15.574+0600] {process_utils.py:132} INFO - Sending 15 to group 47082. PIDs of all processes in the group: [47082]
[2025-03-10T00:27:15.574+0600] {process_utils.py:87} INFO - Sending the signal 15 to group 47082
[2025-03-10T00:27:15.575+0600] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-10T00:27:15.619+0600] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/shamim/airflow_venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/RT_temp.py", line 62, in extract_data
    .awaitTermination()
  File "/home/shamim/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-03-10T00:27:15.637+0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/RT_temp.py", line 62, in extract_data
    .awaitTermination()
     ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-03-10T00:27:15.643+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T00:27:15.644+0600] {logging_mixin.py:190} INFO - Task start:2025-03-09 18:17:16.663042+00:00 end:2025-03-09 18:27:15.642903+00:00 duration:598.979861
[2025-03-10T00:27:15.645+0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data_task> dag:<DAG: real_time_e2e_dag> dagrun:<DagRun real_time_e2e_dag @ 2025-03-09 18:16:22.934679+00:00: manual__2025-03-09T18:16:22.934679+00:00, state:running, queued_at: 2025-03-09 18:16:22.965734+00:00. externally triggered: True>
[2025-03-10T00:27:15.645+0600] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-03-10T00:27:15.646+0600] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=real_time_e2e_dag, task_id=extract_data_task, run_id=manual__2025-03-09T18:16:22.934679+00:00, execution_date=20250309T181622, start_date=20250309T181716, end_date=20250309T182715
[2025-03-10T00:27:15.685+0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T00:27:15.752+0600] {process_utils.py:80} INFO - Process psutil.Process(pid=47082, status='terminated', exitcode=2, started='00:17:16') (47082) terminated with exit code 2
